/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FsEstimatedVirtualList: typeof import('./src/components/FsEstimatedVirtualList.vue')['default']
    FsVirtualList: typeof import('./src/components/FsVirtualList.vue')['default']
    FsVirtualWaterFall: typeof import('./src/components/FsVirtualWaterFall.vue')['default']
    FsWaterFall: typeof import('./src/components/FsWaterFall.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
